### ISSUE TITLE
Package doesn't contain dist

### ISSUE THREAD

**Issue by JanKubicek** [CatHood0/quill-delta-from-html#1]
It is not possible to use package when I downloaded from NPM.
<img width="914" alt="quill_to_html" src="https://github.com/user-attachments/assets/f710a98b-dbfa-4075-a23e-3d712d149aae">

It doesn't not contain any dist folder and it's missing some key properties in package.json.
I have never published package myself, so maybe I'm missing something.

This could help https://cameronnokes.com/blog/the-30-second-guide-to-publishing-a-typescript-package-to-npm/ or there are plenty of other articles.

**Comment by CatHood0** [comment]
> It doesn't not contain any dist folder and it's missing some key properties in package.json.

Thanks, it's my first time creating a package for NPM and idk so much about. I'll fix this soon

**Comment by CatHood0** [comment]
This already was fixed at the 1.0.3 version
